### ISSUE TITLE
design refresh

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#1]
"Models of the Hydrogen Atom" is being ported from Java, see http://phet.colorado.edu/en/simulation/hydrogen-atom.  

Review the Java version to see how its design should be refreshed/revised.

@amyh-phet I believe that @ariel-phet assigned this to you. Feel free to handle however you feel best (Google Doc, comments in this issue, ...)  Note that this sim has 2 features in the Help menu (Legend, Transitions) that need to move to the play area.

**Comment by amyh-phet** [comment]
@pixelzoom   I'm currently working on a design doc in Google drive.  Do we have a time frame for when you will begin this port?

**Comment by ariel-phet** [comment]
@amyh-phet I think that will depend a bit on what your review of the sim produces. If basically we are just making aesthetic changes (breaking into screens, face lifting etc), then I think @pixelzoom will be comfortable porting over the model and such. However, if we are envisioning any feature changes (ideally not), then it might be a longer time line before beginning the port.

**Comment by pixelzoom** [comment]
I've already started porting.

**Comment by pixelzoom** [comment]
Hard for me to envision how this sim could end up as multiple screens. Unless your considering a screen for each model? That was considered during the original Java design, and it was decided that being able to quickly compare models on the same screen was fundamental to the learning goals.  The number of models (6) would also be problematic for HTML5 sims, where are upper limit is typically 4.

**Comment by amyh-phet** [comment]
I think that keeping all models on the same screen would be the best way to go.  The only way I could see this being multiple screens would be to have two screens - experimental and then prediction (with all models).  I don't think this is necessary and would make comparing experimental and predicted a bit more difficult.   I think the major changes would be in layout and updated artwork for things like the light "gun".    I think the biggest challenge will be to incorporate the 2 features from the Help menu into the playspace without making it visually crowded.     

As far as feature changes, I think the current sim function is good and supports student achievement of learning goals.   No need for major changes to features.

**Comment by pixelzoom** [comment]
Moving experimental and prediction to separate screens would make it cumbersome to compare the various models ("prediction") to reality ("experment"), which was also fundamental to the learning goals, as I recall.

**Comment by pixelzoom** [comment]
For the "Legend" feature, having it in the Help menu never made sense to me, since it's already shown in the play area - see screenshot below.    The only time it's *not* shown in the play area is when you switch to "Experiment", which would be easy to change.

![screenshot_63](https://cloud.githubusercontent.com/assets/3046552/11192290/79179ae0-8c5d-11e5-93f9-d0158bc81f80.png)

**Comment by pixelzoom** [comment]
The "Transitions" dialog is related to the light control when it's in "Monochromatic" mode, so you can dial in specific wavelengths.  So it might be most useful if this dialog were made accessible from within the light control.

**Comment by amyh-phet** [comment]
I think it makes sense to keep this sim to one screen.  Your suggestions for "Transitions" and "Legend" sound good - might need to rearrange a few of the control panels to make room for the transitions info.

**Comment by pixelzoom** [comment]
@amyh-phet another design issue... In the java version, the playback control are at the bottom center of the screen (see screenshot above).  In HTML sims, that area is taken by the navigation bar, and screen-specific elements (controls, etc) cannot be put in (or on) the navigation bar.  So we'll need to find space for the playback controls in the play area (above the navigation bar).

**Comment by amyh-phet** [comment]
@pixelzoom   I think we will run into many design issues with this one.   I'm working on a new layout today - lots of things to fit and not a lot of space.

I do have one question about the spectrometer from the Java version.  In Java, you could take a snapshot of the spectometer, save the snapshot, and then compare it to snapshots from other models or the experiment mode. I know in Java you could move the snapshots around as it generated a separate window.  What does this interaction look like in HTML?

**Comment by pixelzoom** [comment]
It's not actually a separate window in Java, it just looks like a window. We can provide the same presentation and interaction in HTML.

**Comment by pixelzoom** [comment]
@amyh-phet Assuming that we're going to replace the cheesy "ray gun"...  It would nice to reuse something from another HTML5 sim.

Consider using one of the lights from "Molecules and Light":
http://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_en.html

Or the light from "Beer's Law Lab" may be a better choice, because it has room for a big red button: 
http://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_en.html

**Comment by amyh-phet** [comment]
I agree the light ray gun needs to be updated and we should remove the "Turn on the gun" prompt when the sim opens.  In the current mock up I used a variation on the Beer's law light source.  The version I used is in the design mock up for the Rutherford sim.  I can send a screen shot to give you an idea-not at home right now so it will be a bit before I can send it.  I did ask for time at design meeting for this sim.

**Comment by amyh-phet** [comment]
Here's what I have so far.  Happy to discuss further.  
![light_source_models_h_atom](https://cloud.githubusercontent.com/assets/13650180/11231721/ab766ce4-8d68-11e5-8d72-11c11a16c89f.png)

**Comment by pixelzoom** [comment]
Also consider using PhET's new standard "radio button group", which appears in other others. Here's what it looks like in this sim:

![screenshot_68](https://cloud.githubusercontent.com/assets/3046552/11245641/eb919700-8dd0-11e5-8a28-d141122a103a.png)

**Comment by amyh-phet** [comment]
@pixelzoom   and @ariel-phet   I've added the AI files to the MOTHA folder in drive.   Mockups are updated as of 06/26/17, including projector model.

**Comment by pixelzoom** [comment]
Un-deferring, because developer has resumed for this sim.

@arouinfar If there's anything else you'd like changed about the design, now's the time. As I recall, there were open issues in the design doc.

**Comment by arouinfar** [comment]
Unassigning myself until work resumes on this sim.

**Comment by DianaTavares** [comment]
We have a new design working and for now, we have well identified design request. We can close this issue to focus on the details.
