### ISSUE TITLE
User reported issue: Lyman series/Balmer lines

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/models-of-the-hydrogen-atom#13]
> First of all thank you for giving this extra ordinary tool for teaching. I have had the pleasure of teaching both at Uni and at highschools, and have used your simulations extensivly. 
However with you simulation of the hydrogen atom I have a small issue.
When investigating the atom model with monochromatic light the spectral lines are only draw for the Lyman series and not the Balmer lines. I need to put my laser on 656nm  and then only have a red spectral line. 
If you could correct this, the experience would be complete.

**Comment by amyh-phet** [comment]
@oliver-phet   Did the user provide any information about the model they were using when they noticed this behavior?  Trying to recreate issue but finding I need more information to adequately address their concern.

**Comment by pixelzoom** [comment]
@oliver-phet looks like we need more info here.

**Comment by oliver-phet** [comment]
Haven't heard back from user in a month. Closing for now.
