### ISSUE TITLE
generalize LaserPointerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#2]
It's now used in MOTHA, BLL, bending-light.

**Comment by pixelzoom** [comment]
In MOTHA, it's implement programmatically in LightNode.

In BLL, it's an image file (light.png) used in LightNode.

In bending-light, it's 2 image files (laser.png, laser_knob.png), with or without a "knob". The laser has a knob if it's both rotatable and translatable, no knob if it's only rotatable.  Very odd, because when a knob is present, the knob is used to do rotation.

**Comment by pixelzoom** [comment]
The name LightNode is a bit too generic for this.  How about LaserPointerNode? 

Here's the node:
![screenshot_95](https://cloud.githubusercontent.com/assets/3046552/11723781/5884090c-9f2d-11e5-8c25-8339bd97c6a6.png)

Here's a real laser pointer:
http://martinjclemens.com/laser-pointers-the-new-ufo-menace/

@samreid What do you think about the name LaserPointerNode? Or something else?

**Comment by pixelzoom** [comment]
Generalization is done.  Remaining tasks:

• move to scenery-phet, change namespace
• address memory leak in sun (see TODO in code, line 86)
• use in beers-law-lab
• create issue to use in bending-light

**Comment by samreid** [comment]
LaserPointerNode is the best name I've heard so far, with LaserNode a close second.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/commit/29b5edf977023ff83f4fe60a81a94055e1fe787a, I removed the short-circuit of `button.dispose`, after adding stubs to sun buttons.  Note that LaserPointerNode will leak until those stubs are implemented.

**Comment by pixelzoom** [comment]
LaserPointerNode is now used in beers-law-lab.LightNode, which had been instrumented for PhET-iO. LightNode was not calling `tandem.addInstance`, but it seemed like LaserPointerNode should.  But without an answer to https://github.com/phetsims/beers-law-lab/issues/131, I''m not sure.

Assigning to @samreid to:

(1) Verify that it's correct to call `tandem.addInstance` in LaserPointerNode, and

(2) Do a general review of LaserPointerNode (which may make sense to do at the same time as https://github.com/phetsims/bending-light/issues/339)

**Comment by samreid** [comment]
The formatting is inconsistent here, I'll choose the most prevalent style which appears in 3 of the 4 sites:

```js
    /**
     * Sets the enabled state of the laser's button.
     * @param {boolean} value
     * @public
     */
    setEnabled: function( value ) {
      this.button.enabled = value;
    },
    set enabled( value ) { this.setEnabled( value ); },

    /**
     * Gets the enabled state of the laser's button.
     * @returns {boolean}
     * @public
     */
    getEnabled: function() {return this.button.enabled; },
    get enabled() { return this.getEnabled(); }
```

**Comment by samreid** [comment]
I noticed this line:

```js
options.children = [ nozzleNode, bodyNode, this.button ];
```

This means any children passed in through the options would be overwritten.  Two potential solutions to this:
* assert that options.children is undefined or empty array before setting it
* append to the children array instead of overwriting it.

I'll leave a checkbox here for when this comment has been addressed:
- [ ] comment addressed

**Comment by samreid** [comment]
I noticed this default:

```js
buttonTouchExpansion: 15,
```

But I thought we had decided that common code wouldn't expand touch areas by default?

**Comment by samreid** [comment]
We spent time on ProbeNode making sure the light came from the top left no matter how the ProbeNode was oriented, but it looks like the gradients in LaserPointerNode are hard-coded.  Should we address this?

**Comment by samreid** [comment]
When developing a scenery-phet or sun component, it is good to add a sample usage in the example main.  Can we do that for LaserPointerNode?

**Comment by samreid** [comment]
Is it redundant to put `@public` on a constructor?

**Comment by samreid** [comment]
Review summary: LaserPointerNode.js is in good shape.  It is well organized and well-commented, nice work!  If I have any other suggestions after integrating into bending light, I'll create separate issues.  Back to you @pixelzoom.

**Comment by samreid** [comment]
One more thought, I saw this code:

```js
tandem: options.tandem ? options.tandem.createTandem( 'button' ) : null
```

and realized it is a bit more idiomatic for us to use `&&` instead in cases like this:

```js
tandem: options.tandem && options.tandem.createTandem( 'button' )
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2#issuecomment-170305861, @samreid said:
> But I thought we had decided that common code wouldn't expand touch areas by default?

We decided that common-code that was not PhET-specific (sun, scenery, etc.) would not set defaults, that PhET-specific common-code (eg, scenery-phet) would set defaults that were appropriate for typical PhET uses.   LaserPointerNode is in scenery-phet, so it's setting a default that's typically useful for PhET.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2#issuecomment-170306296, @samreid asked:
> Is it redundant to put @public on a constructor?

This is a more general discussion than I'd like to have here. If you want to pursue it, please open a general issue and label for developer-meeting.

**Comment by pixelzoom** [comment]
Addressed comment https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2#issuecomment-170305019:

```js
// add any children specified by the client
options.children = [ nozzleNode, bodyNode, this.button ].concat( options.children || [] );
```

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2#issuecomment-170305922, lighting direction...  Good point, I'll have a look.

@samreid How do you intend to address this in Bending Light, where the laser is dynamically rotated?

**Comment by pixelzoom** [comment]
LaserPointerNode added to 'Components' screen of scenery-phet demo application.

**Comment by pixelzoom** [comment]
Re lighting cues, there are 2 issues:

(1) The button:
The button may be either `RoundMomentaryButton` or `RoundStickyToggleButton`, neither of which has a convenient API for setting lighting cues.  The easiest thing to do would be to rotate the button, by adding something like `options.buttonRotation`.  Is that sufficient? 

(2) The body
As exhibited in bending-light, the orientation of this node can be arbitrary.  I don't think we should attempt to address that.  I think that the gradient direction should always be perpendicular to the direction that the laser is pointing, so that the specular highlight is parallel to the laser direction.  If we agree on that, then the lighting can be changed via existing options: `topColor`, `middleColor`, `bottomColor`.   And it may be useful to export the default values via LaserPointerNode.DEFAULT_OPTIONS.  Does that sound sufficient?

Back to @samreid for feedback.

**Comment by pixelzoom** [comment]
I implemented what I described in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/2#issuecomment-170616548 for lighting cues.  I needed to add one additional option, `highlightColorStop`, in order to shift the specular highlight.  See the scenery-phet demo for an example.

All issues have been addressed.  Back to @samreid for review.

**Comment by samreid** [comment]
Changes look great, the last thing I would recommend for this file is to document (in the DEFAULT_OPTIONS) for the nozzle if its width is parallel to the laser direction or perpendicular.  For someone unfamiliar with the sim, they may think the nozzle width is how wide it is (perpendicular).

**Comment by samreid** [comment]
I guess the same argument applies to the laser body itself.  The code appears that the width is along the parallel axis, which makes sense for a normal 2d rectangle, but not when referring to the dimensions of a laser pointer.  Imagine a laser pointer pointing up like in the MOTHA example above.  What would you call the laser pointer `width` in that image?

Not recommending a specific action at this point, just want to discuss it to understand what's best.

**Comment by pixelzoom** [comment]
The JSdoc defines this component's default orientation:

`* Default orientation is pointing to the right. Origin is at right center (the edge of the output nozzle).`

As with any UI component, I would expect the semantics of all options to be relative to the non-transformed orientation.  And since we're dealing with the view coordinate frame, I would expect `bodySize` and `nozzleSize` (both `Dimension2`) to be view dimensions.  So I think we should leave them as is.

**Comment by samreid** [comment]
Sounds good since developers will have to be familiar with the default orientation.  I think we're done here, nice work.

**Comment by pixelzoom** [comment]
Thanks for the thorough review!
