### ISSUE TITLE
Use TimeControlNode for Play/Pause/Step buttons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/models-of-the-hydrogen-atom#20]
From phetsims/scenery-phet#561. A scenery-phet/TimeControlNode was created that combines the PlayPauseButton and StepForwardButton and includes PhET-iO and PDOM instrumentation. It should be used in this sim. Assigning to responsible dev.

**Comment by pixelzoom** [comment]
Specifically, this should replace `MOTHA/TimeControls`, which predates the existence of `SCENERY_PHET/TimeControlNode`.

**Comment by pixelzoom** [comment]
On 3/12/2020 I looked at using scenery-phet/TimeControlNode.  It only supports normal & slow speeds.  This sim needs normal, slow, fast.

**Comment by jessegreenberg** [comment]
This will be added soon in https://github.com/phetsims/scenery-phet/issues/575.

**Comment by pixelzoom** [comment]
This was done a couple of weeks ago, and I forgot to close.
