### ISSUE TITLE
Artwork needed for "Classical Solar System" model (Kaboom!)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#28]
The "Classical Solar System" model has a "Kaboom" image (images/kaboom.png), that looks like this:

![kaboom](https://user-images.githubusercontent.com/3046552/173694585-e1dfa0d1-f944-4c54-967f-e03f884ee7fd.png)

Here it is in context, in the Java version. It is shown when the atom is destroyed.

<img width="1022" alt="screenshot_1697" src="https://user-images.githubusercontent.com/3046552/173694618-0bd000cf-8443-473b-9156-ffbfc6355c96.png">

This image has a couple of problems:

(1) Its background is not transparent, it's black. So it doesn't work with projector mode.
(2) The "Kaboom!" text is part of the image, so is not translatable.

@arouinfar please provide revised artwork, and guidance on how you'd like the "Kaboom!" text to be handled.

**Comment by pixelzoom** [comment]
Here's how it currently looks in projector mode in the HTML5 version:

<img width="1031" alt="screenshot_1698" src="https://user-images.githubusercontent.com/3046552/173703635-116e4452-47fe-44cf-9db5-8f7142af3fb4.png">

**Comment by arouinfar** [comment]
Unassigning myself until work resumes on this sim.

**Comment by pixelzoom** [comment]
Do we even need the "Kaboom!" string?  I think not.

**Comment by DianaTavares** [comment]
No, we don't need the words. In the design meeting on August 13, we decided to go with the "My Solar System" sim animation, just that in this case, both bodies disappear. 
![Explosion](https://github.com/user-attachments/assets/2254e9f5-400a-4adc-ba01-29c00ce5f89a)

**Comment by pixelzoom** [comment]
In 8/15/24 design meeting, there were questions about how the My Solar System animation would work. For example, what would be displayed after the animation completes?  The consensus was that the existing "Kaboom!"graphic would be OK, if we removed the black background from the image file, and removed the "Kaboom!" text.   I recall creating this image using a Photoshop plugin. I'll check to see if it still exists on my old Mac Pro server, and see if I can recreate it.

**Comment by pixelzoom** [comment]
> I'll check to see if it still exists on my old Mac Pro server, and see if I can recreate it.

Unfortunately, no such luck.

We'll need to have someone create new artwork.

**Comment by DianaTavares** [comment]
Well, we can back to the idea of my solar system animation, and maintain the big star that represents the explosion 

![image](https://github.com/user-attachments/assets/32611f24-3904-4c22-8ae2-d85631050a5c)


or, what type of file needs to be the explosion artwork? Probably I can ask Mayra to create it (she is the one that does our social media publications and knows how to use several graphic programs.

**Comment by pixelzoom** [comment]
I'd rather not add the animation. It's a significant amount of extra work, and feels unnecessary. It also doesn't look like an atomic explosion :)

We'll need a .png file, since it needs to have a transparent background.  We'll also need the original "asset" file (.ai, .psd,...) that was used to create it.

**Comment by DianaTavares** [comment]
It was decided to continue with this artwork:
![SS explosion](https://github.com/user-attachments/assets/63f6c52e-feda-4b00-9e85-53ad7edff1f3)

I already submitted the .psd and .png files in the image folder in GitHub.

**Comment by pixelzoom** [comment]
In the above commits:
* Renamed the artwork and put the files in the correct folders.
* Scaled down the .png file because it was unnecessarily huge, and would bloat the .html file.
* Add attribution to license.json and credits.

@DianaTavares please review, including the credits. Close if OK.

**Comment by DianaTavares** [comment]
Looks perfect! Thanks!!
