### ISSUE TITLE
Presentation of Transitions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#32]
Related to #1 design refresh ...

In the Java version, selecting _Help > Transitions..._ opened the "Transitions" dialog, as shown below.

<img width="1019" alt="screenshot_1745" src="https://user-images.githubusercontent.com/3046552/177396263-43f081e8-a264-481d-8ccc-99e2c54eaeed.png">

For the HTML5 version, here's what the [design doc](https://docs.google.com/document/d/1BH23koSJwLpR1yUcOviiI2ixrpHH0qBaksbplPk5NkU/edit?pli=1) currently says about the Transitions:

<img width="691" alt="screenshot_1746" src="https://user-images.githubusercontent.com/3046552/177396628-a623c197-4c7e-4825-8e4e-442b686fc94a.png">

But my recollection is that this was still a bit "up in the air".  Assigning to @arouinfar to finalize.

**Comment by pixelzoom** [comment]
7/14/2022 design meeting:

Consensue was that an info button will be shown in the Electron Energy Level diagram, as shown in the HTML5 design doc.

**Comment by arouinfar** [comment]
Unassigning myself until work resumes on this sim.

**Comment by pixelzoom** [comment]
This is going to be combined into the UI for selection absorption wavelengths.  See https://github.com/phetsims/models-of-the-hydrogen-atom/issues/31.

**Comment by pixelzoom** [comment]
I think we can close both this issue and #31.   When the sim is feature complete, we can reevaluate and (if needed) open a new issue for any changes that we'd like to make.
