### ISSUE TITLE
Light and time controls are not visually separated/grouped.   

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#35]
Related to #1 design refresh ...

The Java version, while a little klunky, has good visual separation between the gun (aka light) controls and the time controls:

<img width="1024" alt="screenshot_1754" src="https://user-images.githubusercontent.com/3046552/177400875-caa7d876-18ef-4f12-8103-ca3ddb49316d.png">

In the HTML5 version, related controls are grouped together very well, creating a bit of a UI mess in the lower-left of the screen. The separation/grouping here is not good, making it difficult to parse visually.

<img width="1092" alt="screenshot_1753" src="https://user-images.githubusercontent.com/3046552/177401042-f78a19b8-8dc7-41ce-856a-1ed2c1c24210.png">

@arouinfar thoughts on how to improve this?

**Comment by pixelzoom** [comment]
7/14/2022

For time controls, we'd like to reduce to 2 speeds, "normal" and "fast".  Make the "normal" speed a bit slower than it is.

Also decide if we want the Step button dt to be constant, or a function of the speed selected.

**Comment by pixelzoom** [comment]
> Also decide if we want the Step button dt to be constant, or a function of the speed selected.

@arouinfar what would you like?  Do you want the dt for the Step button to be the same for both speeds?  Or should the dt be larger for "Fast"?

**Comment by pixelzoom** [comment]
@arouinfar I've added a `timeScale` query parameter.  You give it 2 numbers, which multipliers for dt in Normal and Fast modes (in that order).  The default is `timeScale=1,2`.  Let me know what you'd like as the default.

**Comment by arouinfar** [comment]
Unassigning myself until work resumes on this sim.

**Comment by pixelzoom** [comment]
From "Latested mockups (9/19/22)" in the design doc, the light controls now look like this:

<img width="355" alt="screenshot_3434" src="https://github.com/user-attachments/assets/ebf02004-c56f-4a0b-8ab9-70d230657d08">

**Comment by pixelzoom** [comment]
Implementation now matches the design (with some differences that we can discuss later) so this issue can be closed.
