### ISSUE TITLE
[Documentation] Write a better README.md

### ISSUE THREAD

**Issue by gambhirsharma** [phetsims/models-of-the-hydrogen-atom#40]
While exploring the repo it was challenging for me to navigate it.

A Better README file could solve this issue and encourage more developers to join this open-source project.

Things need to improve:
- Contribute Rules and Guidelines.
- All tech stack used in this project.
- A GitPod link.
- Provide live hosted simulations link.
- Provide some Screenshots of the projects.
- A short description of the principle of the projects.
- Contributor list. etc...

**Comment by pixelzoom** [comment]
Hi @gambhirsharma. Thanks for the input.   

All PhET README.md files are generated automatically from templates.  There are different templates for published and unpublished simulations.

As noted in [the README.md for models-of-the-hydrogen-atom](https://github.com/phetsims/models-of-the-hydrogen-atom/blob/master/README.md):

> _This simulation is under development and has not been published._

So models-of-the-hydrogen-atom is an unpublished sim, still in development, and not ready for public consumption. As such, it intentionally does not (and cannot) have many of the things that you've suggested in its README.md file.

When a simulation has been published, it's README.md file is regenerated as part of the PhET build process. And itt includes the type of information that you've suggested. For example, see [the README.md file for geometric-optics](https://github.com/phetsims/geometric-optics/blob/master/README.md).

If you're like to learn more about PhET's open-source community, please see the "Get Involved" section of the README.md for any published sim.

Would you like to add anything else, or can I close this issue?

**Comment by gambhirsharma** [comment]
Ok, Now it's clear to me.

You can now close this issue.
Thanks for your time, Have a nice day ahead :)

**Comment by pixelzoom** [comment]
👍🏻 closing.
