### ISSUE TITLE
screen names needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#5]
The design document identifies the 2 screens as "Screen 1" and "Screen 2" (or in one place, "Screen 2 - Electron Energy Levels").   In order to structure the GitHub repository, I need to know what the actual screen names are.

**Comment by amyh-phet** [comment]
@pixelzoom    Let's try Spectra as the label for Screen 1 and Energy Levels as the label for Screen 2.  I'll update the design doc to reflect this change.

**Comment by pixelzoom** [comment]
Screen names assigned to GitHub directories and file names in @298d9e9604a74759489d099666578982e7806067.  Closing.
