### ISSUE TITLE
screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#6]
Icons needed for the screens.  They are not specified in the design doc. Not needed immediately, but sometime in the next few weeks.

**Comment by amyh-phet** [comment]
@pixelzoom   Can do.  I'll likely get to these at the end of the week.

**Comment by amyh-phet** [comment]
Emailed on 06/19/2017.  Guess that took more than a week.

**Comment by pixelzoom** [comment]
Thanks @amyh-phet, .ai file is checked in to github.

**Comment by pixelzoom** [comment]
Un-deferring, since development has resumed for this sim.  @arouinfar is the new responsible designer, so assigning to her.  My guess is that icons will be needed around the beginning of September 2022.

**Comment by arouinfar** [comment]
Looks like the .ai asset for the screen icons was checked in [here]( https://github.com/phetsims/models-of-the-hydrogen-atom/blob/master/assets/motha-screen-icons.ai), but the icons weren't exported and added to the images directory.

@pixelzoom here are the images for the screen icons. Please let me know if there is anything else you need here.
[energyLevelScreenIcon.png](https://user-images.githubusercontent.com/8419308/177639958-fd280fc9-0c9b-4eff-89b7-b8d8443f5b51.png)
[spectraScreenIcon.png](https://user-images.githubusercontent.com/8419308/177639960-980e8e84-683a-4e18-b43e-0fa326a0aa65.png)

**Comment by pixelzoom** [comment]
Thanks @arouinfar. I integrated the screen icons in the above commit. See screenshot below. Closing.

<img width="1218" alt="screenshot_1759" src="https://user-images.githubusercontent.com/3046552/177670679-91a131cd-6978-4ed8-bdd6-d98225858776.png">

**Comment by pixelzoom** [comment]
Good catch. When I downloaded them from this issue, GitHub gave them nonsense file names.  Swapped in the above commit, screenshot below. Closing.


<img width="1169" alt="screenshot_1762" src="https://user-images.githubusercontent.com/3046552/177867004-aeb00100-ef32-496b-8a7e-59fc54f4f741.png">
