### ISSUE TITLE
Add slow option in the play control and change electron color. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#60]
Thinking in solve #57, one way to make easier to see the absorption and emission of the photons, and the impact of that on the electron, it was decided in the Sep 05 design meeting to add the slow option:

![image](https://github.com/user-attachments/assets/b914a416-6f07-493e-a9d7-ac26f7f69598)

and change the color of the electron to a lighter blue (like CCK)

**Comment by pixelzoom** [comment]
Ready for review by @DianaTavares. See screenshots below. 

I added "Slow" to the time controls.

For electrons, CCK uses a Circle with 3 colorstops, while MOTHA uses a ShadedSphereNode with 2 color stops (base color and highlight color).   So I could not directly use any colors from CCK, and I took my best guess.   The colors I used are:

electronBaseColor = rgb( 108, 186, 223 )
electronHighlightColor = rgb( 169, 214, 231 )

If you'd like something different, please use the Color Editor (via phettest) to experiment with colors, and tell me what rgb values you'd like for both of the above colors.

Also keep in mind that colors need to be colorblind-compliant, and they need to also work for Projector Mode.

<img width="958" alt="screenshot_3490" src="https://github.com/user-attachments/assets/9e8de93f-2bb0-44f1-b795-75f46a69c479">
<img width="955" alt="screenshot_3491" src="https://github.com/user-attachments/assets/c71cb28e-e054-4807-8f7b-83eb990f3a9f">

**Comment by pixelzoom** [comment]
@DianaTavares please also review how fast the sim runs at Fast, Normal, and Slow settings.  If you'd like to try different speeds, you can use the `timeScale` query parameter.   The default is `timeScale=2,1,0.5`, where the values are the scale factors for Fast, Normal, Slow (in that order).  And I recommend keeping Normal as 1.

**Comment by DianaTavares** [comment]
I love the new color in the Black background, but it doesn't look good in the projector mode. We can have 2 different colors, one for black and the other for white, right? 

The actual is:
![image](https://github.com/user-attachments/assets/f4b9e1ad-8228-41ee-ae61-fc2927c1912c)

I think it needs to be darker:
 
![image](https://github.com/user-attachments/assets/b4810288-c124-4150-8c80-3f2d78ac3b84)

The electronBaseColor is `6,144,249` and the electronHighlightColor is `172,217,251`

and both look good in the colorblindness test!

We continue playing slow control!

**Comment by DianaTavares** [comment]
O played with velocity of Slow, and I think I got something close to the java with timeScale=0.2 for slow.  With than velocity is easy to distinguish the photons emitted, the problem is that I sometimes lost the electron but only in the Bohr. I will let @arouinfar and @Nancy-Salpepi to play with that control and see if they have ideas. 

Diana's idea: 
I see that the sim has 2 ways to let the user know where the electron is, (the electron and the n label in the corner of the panel). One idea that I have is to make a change in that number more evident, like changing its color to yellow when a change happens, and then comeback to white, in that way, we don't affect the movement view. 

Probably I am just overthinking this and there is not a problem with slow velocity because the user has time to see that the electron is not more in n=1, and look for it in the sim before its decay. Waiting for @arouinfar and @Nancy-Salpepi comments.

**Comment by pixelzoom** [comment]
Checking the Java implementation (`HAConstants.CLOCK_STEPS`), the relative speeds would be `timeScale=3,1,0.25`.

**Comment by pixelzoom** [comment]
ELectron colors have been adjusted for projector profile, as requested, screenshots below. @DianaTavares please review.

<img width="120" alt="screenshot_3496" src="https://github.com/user-attachments/assets/2fe43803-1eea-4791-b812-aa056724c0bd"><img width="123" alt="screenshot_3497" src="https://github.com/user-attachments/assets/ec9748e8-5ee9-4787-8284-55443f2f4d72">

**Comment by Nancy-Salpepi** [comment]
>Checking the Java implementation (HAConstants.CLOCK_STEPS), the relative speeds would be timeScale=3,1,0.25.

I like these speeds. At 0.25 it is possible to see the photons being absorbed/emitted. Every once in a while it takes a second to find the electron, but I always found it before the photon was emitted. 

>One idea that I have is to make a change in that number more evident, like changing its color to yellow when a change happens, and then comeback to white, in that way, we don't affect the movement view.

I don't think that a color change for "n = x" is necessary, but maybe interviews would let us know if students are having trouble finding the electron despite the slow speed.

**Comment by arouinfar** [comment]
>>Checking the Java implementation (HAConstants.CLOCK_STEPS), the relative speeds would be timeScale=3,1,0.25.
>
>I like these speeds. At 0.25 it is possible to see the photons being absorbed/emitted. Every once in a while it takes a second to find the electron, but I always found it before the photon was emitted

Me too! The animations look reasonable for both fast and slow, and I found it very easy to follow the electron in Slow.

> I don't think that a color change for "n = x" is necessary, but maybe interviews would let us know if students are having trouble finding the electron despite the slow speed.

Agreed! I would wait until interviews tell us that students need additional scaffolding.

**Comment by pixelzoom** [comment]
I've changed the default to `timeScale=3,1,0.25`.

@Nancy-Salpepi if that look good to you, please close.

**Comment by pixelzoom** [comment]
Oh, nevermind @Nancy-Salpepi -- I see that you commented in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/60#issuecomment-2369741979.

Closing.
