### ISSUE TITLE
Change the order in legend & color of photon

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#61]
From September 9 design meeting:

Reorder to proton, electron, photon. “Photon” and “proton” look a bit similar, especially next to each other.

If we change the color of the electron to blue (issue #60), make the photon in the key yellow/green so that the electron and photon look more distinct.

**Comment by pixelzoom** [comment]
The legend has been reordered, and the photon icon is now 530 nm.  See screenshot below.   @DianaTavares please review, close if OK.  If you'd like a different color for the photon, please tell me the wavelength to use -- it's currently 530 nm.  Make sure it works for Projector Mode.

<img width="124" alt="screenshot_3489" src="https://github.com/user-attachments/assets/791d91ea-aafc-4bb3-abff-252d660d859a">

<img width="123" alt="screenshot_3488" src="https://github.com/user-attachments/assets/0468b8dc-58e0-48cf-8dc9-87b3a94dba01">

**Comment by DianaTavares** [comment]
The idea of the green was to better distinguish between the electron and the photon in the legend now that the electron is a lighter color. Green looks like a good idea, but I don't like that I can't see the “star” in the center (as all the photons have).  
I like how this purple looks like in back and white background:

![image](https://github.com/user-attachments/assets/91515415-0461-4c1e-961f-1330dc1d99ed)
![image](https://github.com/user-attachments/assets/951d9414-9f56-471c-a810-33a5f68f3c43)

and it is the 410 nm

**Comment by pixelzoom** [comment]
Photon icon is now 410 nm, screenshots below.  Back to @DianaTavares for review, close if OK.
<img width="149" alt="screenshot_3495" src="https://github.com/user-attachments/assets/1d73d9f9-317b-4796-904b-2566dc7109ef">
<img width="138" alt="screenshot_3494" src="https://github.com/user-attachments/assets/b40d9776-e566-43ed-a79c-1a470e732b5c">

**Comment by DianaTavares** [comment]
Perfect! Thanks!!!
