### ISSUE TITLE
When to show electron state (n) transition information

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#63]
From last design meeting, we have this changes for the experiment view:

- [ ] Hide n-transition readout
- [ ] Hide n-transition column in dialog

**Comment by pixelzoom** [comment]
@DianaTavares ready for review, close if OK.  Note that the transitions in the Absorption/Emission dialog are also hidden if you select a predictive model that does not have the concept of electron state.  For example, select 'Billiard Ball' and you will see no transitions in the Absorption/Emission dialog.

**Comment by pixelzoom** [comment]
Discussed with @DianaTavares, @arouinfar and @Nancy-Salpepi in an improptu design meeting.

[1.0.0-dev.11](https://phet-dev.colorado.edu/html/models-of-the-hydrogen-atom/1.0.0-dev.11) implements the requested behavior that was discussed in 9/19/24 design meeting.

Behavior of `absorptionTransitionText` (the 'n = ...' readout above the monochromatic slider) is good. 

But the consensus is that behavior of the 'n transition' column in the Absorption/Emission dialog is confusing. We're still showing absorption/emission wavelengths (and push buttons) for hydrogen models where there is no concept of absorption/emission (Billiard Ball, Classical Solar System) and where absorption/emission does not correspond to the wavelengths shown (Plum Pudding, which absorbs any wavelength and emits 150 nm).

So we decided to try another approach, which is:
* Hide the Absorption/Emission checkbox and set `absorptionEmissionDialogVisibleProperty` to false for classical models.
* Close the Absorption/Emission dialog (if it's open) for classical models.
* Do not attempt to restore the state of `absorptionEmissionDialogVisibleProperty` when switching back to a quantum model.
* Hide the 'n transition' column of `absorptionEmissionDialog` only for the 'Experiment'.

**Comment by pixelzoom** [comment]
I made the changes that we discussed yesterday in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/63#issuecomment-2369527039.  Ready for review in phetttest or [1.0.0-dev.12](https://phet-dev.colorado.edu/html/models-of-the-hydrogen-atom/1.0.0-dev.12).  @DianaTavares @arouinfar @Nancy-Salpepi please provide your feedback.

**Comment by DianaTavares** [comment]
I reviewed them in dev.12 and they look great with the classic models!! my only question is with the experiment, that doesn't include the checkbox:
![image](https://github.com/user-attachments/assets/941d6580-187f-43a7-a261-23defe4f7636)

I try to open the panel and move to experiment and the panel hides the transitions (that is great!), But I remember correctly that the experiment needs the checkbox:
![image](https://github.com/user-attachments/assets/d7a65873-ea8f-4ce0-94e4-18ad2146cad2)

**Comment by pixelzoom** [comment]
>  my only question is with the experiment, that doesn't include the checkbox:

Oops. Thanks @DianaTavares, good catch.  Fixed in the above commit, back to you to verify.

**Comment by arouinfar** [comment]
@pixelzoom the behavior on main looks pretty good, but I found an edge case that feels odd.

On startup (in Experiment mode) check Absorption/Emission to open the dialog.  Switch to Model mode, and the selected model should be Billiard Ball. The Absorption/Emission checkbox is hidden, but the dialog remains open, but now has the n transition column. I would expect the dialog to be automatically hidden when switching over to a classical model.

**Comment by pixelzoom** [comment]
> ... but I found an edge case that feels odd.

You are too kind. It's a bug, not an edge case :)

This is really complex to implement, and (as you can see) I'm having a hard time getting it right. Since implementation complexity is often inversely related to usability, let's say I'm having concerns about this feature.

**Comment by pixelzoom** [comment]
The bug that @arouinfar reported in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/63#issuecomment-2372562548 is fixed, so ready for another look.

**Comment by DianaTavares** [comment]
Sept 26 design meeting with DL, AR, NS, and KP

The updated flow looks good!

It is a question about the closing button that AR will add to the agenda. 

We can close this issue and, and create a new one if after the designers meeting we have a change in the appearance of that button.
