### ISSUE TITLE
Highlight “arrows” in the Electron Energy Level Diagram

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#64]
2 teachers (from 9) during the feedback process commented that is challenging to see the arrows in the electron energy diagram (specially the gray-ones that correspond to UV photons):
![image](https://github.com/user-attachments/assets/0fd47018-6e59-437b-b775-99a730c034ae)

Those arrows change their colors depending on the photon, so it should stay gray, red, etc. To solve this problem, the arrow head could be bigger, and also I think that the stroke can be a little bigger. 

But, I see that the in the old mockups, that panel is black, that in general will make all the colors more contrasting:
![image](https://github.com/user-attachments/assets/a91e2e28-e371-4ac2-9aea-6536ae3e4b50)

The problem is that is not a solution for the projector mode, where the panels should be white. For me, it is difficult to play with those mockups, and draw lines with different curves as the sim proposes (because each arrow also represents the wavelengths with different numbers of curses). Then I am going to wait until @pixelzoom implement the panel in the sim, and later play with the colors of the panel,the strokes and the arrows heads.

**Comment by pixelzoom** [comment]
This issue overlaps with https://github.com/phetsims/models-of-the-hydrogen-atom/issues/33, so I'm going to close this issue, and we can continue fine tuning the Electron Energy Level diagrams in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/33.  Specifically, https://github.com/phetsims/models-of-the-hydrogen-atom/issues/33#issuecomment-2549470721 mentions problems with the arrow head, and recommends getting rid of them altogether.
