### ISSUE TITLE
include the letters “s”, “p”, “d”, “f”, “g” etc

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#65]
User comment:
The use of the letters s, p, d etc. for the quantum numbers of the orbital moment ℓ, is rooted since high school when studying the chain rule in chemistry courses, and its use is very common in crystal field theory and high-temperature superconductivity (for example, the shape of d orbitals).
It also gives the possibility of increasing the number of open challenges, using this nomenclature, such as, for example, “Find visually the 2D clouds of d-type transitions in the Hydrogen atom”.
This letter nomenclature could be added to the Schrödinger energy level diagram of the Hydrogen atom in the PhET simulation.

![image](https://github.com/user-attachments/assets/3bd5a4f2-2f0a-4112-b584-3662efd53d18)

2D visualization of a cloud in the Schrödinger model, which defines the orbital angular momentum l, for a specific transition according to the energy level diagram, in this case it is an s orbital.

During the 18 September design meeting, we commented that the data can go next to the nlm readout in the observation window, and also @Nancy-Salpepi commented in slack that and info button that says what n, l and m mean can be useful. This is the idea for now, And I will work in the information for the info button: 

![image](https://github.com/user-attachments/assets/216148ed-e77a-43fa-8d1e-5eb3abf1f9c5)

**Comment by pixelzoom** [comment]
What is full set of letters, and how does nlm map to those letters?

**Comment by Nancy-Salpepi** [comment]
The letters correspond to the l values only.
0 =s
1 = p
2 = d
3 = f
4 = g
5 = h

**Comment by arouinfar** [comment]
> What is full set of letters, and how does (n,l,m) map to those numbered letters?
>> The letters correspond to the l values only.

And the number preceding the letter is the n-value.

**Comment by Nancy-Salpepi** [comment]
I responded in the MotHA slack channel but too late...
>It's not clear whether to italicize the subshell letter, for example 2p vs 2p. For now I have not italicized. @Nancy-Salpepi your opinion?

The letters are italicized. 

>I asked in Slack#models-of-the-hydrogen-atom, and the letter s, p, etc. is the "subshell", while 1s, 2p, etc. is the "orbital". Those are the terms that I've used in the code.

3s, 3p, 3d etc can refer to either subshells or orbitals. For example in the 3d subshell there are 5 3d orbitals. the letters without the number -- s, p, d, f -- are usually referred to as orbitals because they are referring to a specific shape (eg. the s orbital has a spherical shape).

**Comment by DianaTavares** [comment]
I am working on the content of the info button. @arouinfar and @Nancy-Salpepi, what do you think about this? (I taket the pictures from the Java sim, but we can use the projector view to have the white background, and in the info button the idea is that the pictures have the same size. I take the information from [here.](https://chemed.chem.purdue.edu/genchem/topicreview/bp/ch6/quantum.html)):

--------------- info panel content-----------------
n, ℓ, and m are the quantum numbers that describe the size, shape, and orientation in space of the orbitals on an atom.

**n is the Principal Quantum Number** and describes the energy of an orbital
 
**ℓ is the Angular Quantum Number** and describes the shape of the orbital. Orbitals have shapes that are best described as spherical (l = 0, or also called s), polar (l = 1 or also called p), or cloverleaf (l = 2 or also called d). They can even take on more complex shapes as the value of the angular quantum number becomes larger.

![image](https://github.com/user-attachments/assets/ab671bb8-5bab-4ace-9151-201ac35be2e6)
Example of a s orbital, in the energy level 2 (2s)

![image](https://github.com/user-attachments/assets/91209ad6-aa9d-404d-ae71-073d675fe0a4)
Example of a p orbital, in the energy level 2 (2p)

**m is the Magnetic Quantum Number,** and describes the orientation of the orbital in space.
  
![image](https://github.com/user-attachments/assets/5ceca36a-d52f-431f-9275-1551552d16c3)
Example of an orbital 3p, with m=1

![image](https://github.com/user-attachments/assets/22527348-949e-497b-acc7-7832f8c21cf1)
Example of an orbital 3p, with m=0

**Comment by pixelzoom** [comment]
Are you suggesting that we put images in the dialog? That's going to be very expensive.  We cannot use screenshots, they would need to be generated from a Schrodinger model + view.  If there's any way that we can do this with text only, let's do that.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/models-of-the-hydrogen-atom/commit/1876a21f822836e9d6c82f173ea47ece231265eb, the orbital letters are displayed in italics, as recommended by @Nancy-Salpepi in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/65#issuecomment-2372638827.

I should also mention that since the oribital letters are translatable, we cannot have a PhET-iO property like `subshellProperty: Property<string>`.   PhET-iO elements cannot contain locale-specific values because doing so would change (and therefore break) the PhET-iO API.

**Comment by DianaTavares** [comment]
Yes, my suggestion was to use pictures (static pictures as example). But if that is not possible, then it can be only this: 

--------------- info panel content-----------------

_n, ℓ,_ and _m_ are the quantum numbers that describe the size, shape, and orientation in space of the orbitals on an atom.

**_n_ is the Principal Quantum Number** and describes the energy of an orbital

**_ℓ_ is the Angular Quantum Number** and describes the shape of the orbital. Orbitals have shapes that are best described as spherical (_ℓ_ = 0, or also called _s_), polar (_ℓ_ = 1 or also called _p_), or cloverleaf (_ℓ_ = 2 or also called _d_). They can even take on more complex shapes as the value of the angular quantum number becomes larger.

**_m_ is the Magnetic Quantum Number** and describes the orientation of the orbital in space

**Comment by DianaTavares** [comment]
> If you want to include the concepts of orbital, shell, and subshell in the Info dialog, then this website has a nice (?) description of n, l, m, and those terms: https://chem.libretexts.org/Bookshelves/Inorganic_Chemistry/Inorganic_Chemistry_(LibreTexts)/02%3A_Atomic_Structure/2.02%3A_The_Schrodinger_equation_particle_in_a_box_and_atomic_wavefunctions/2.2.02%3A_Quantum_Numbers_and_Atomic_Wave_Functions

What do you think @Nancy-Salpepi  about adding information about shells, subshell, and probably ranges of values? I prefer to leave something simple and that can be seen in the simulation. In the sim you can see the size, only shows s and p shapes (then I think is enough to tell "one is spherical and the other is polar shape), and I think only me =0, 1, and probably -1.

**Comment by pixelzoom** [comment]
A first pass at the info dialog has been implemented, see screenshot below.

Dialogs typically have a title, which has not been specified yet. So I chose "Quantum Numbers". Happy to change, let me know what you'd prefer.

The symbols (n, l, m) are not in bold. Doing so will be too much work, and I think the italics already highlights them apart sufficiently.

Putting parts of the text in bold (e.g. **Principal Quantum Number**) is going to complicate translation, as the translator must deal with the markup that makes the text bold. So take that into consideration If it's needed, fine, we do it elsewhere. For example:

```ts
  "nDescription": {
    "value": "{{n}} is the <b>Principal Quantum Number</b> and describes the energy of an orbital."
  },
```

I asked about including the concepts of orbital, shell, and subshell because you're already using "orbital" in all of these definitions.  If I didn't already know what n, l, m are, then I probably will not know what an orbital is.

Let me know what you'd like me to change.

<img width="514" alt="screenshot_3501" src="https://github.com/user-attachments/assets/ef8667b2-aea3-40f3-8589-2544443fd0b7">

**Comment by pixelzoom** [comment]
Do we also want to say something about the purpose of these quantum numbers? Something like:

A solution to the Schrödinger equation, both the three-dimensional wavefunction and energy, includes a set of three quantum numbers ( n,l,ml ). The wavefunction describes an atomic **orbital**, the region in space where the electron is located.

**Comment by pixelzoom** [comment]
In context:

<img width="520" alt="screenshot_3502" src="https://github.com/user-attachments/assets/96d3c524-55e0-44c7-988d-5cb9a47d2427">

**Comment by Nancy-Salpepi** [comment]
I would keep the intro simpler, maybe something like:

>Schrödinger used 3 quantum numbers _(n, l, m)_ to describe the most probable location of an electron, also known as an **orbital.** 


I like n described as:

>_n_, is the **Principal Quantum Number**, and indicates the energy level (shell). 

but if you are going to keep it as describing the orbital, I would change it to "describes the energy and size of the orbital"


For p orbitals, I usually see them referred to as dumbbell-shaped (or even peanut-shaped). 

For d orbitals, only 4 out of 5 are clover shaped, so maybe we should eliminate that part?

**Comment by pixelzoom** [comment]
Here's a revision based on @Nancy-Salpepi's input in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/65#issuecomment-2375236991:

<img width="514" alt="screenshot_3505" src="https://github.com/user-attachments/assets/73dbc885-226f-4ef4-af2d-f7b2a8b002e6">

**Comment by arouinfar** [comment]
I think it's best to keep the contents simple, and the latest iteration in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/65#issuecomment-2375306313 does that well. We provide helpful definitions/context, which is sufficient to support the usage of the sim. If students want to know more, they can look up the terms we provide.

**Comment by pixelzoom** [comment]
Remaining things for this issue:

* Dialog title approval
* Any more changes to dialog content?
* Is using bold in the dialog content worth the translation cost?

**Comment by pixelzoom** [comment]
We decided to change "n" description to:

_n_, the **Principal Quantum Number**, describes the electron’s energy and its probable distance from the nucleus.

**Comment by pixelzoom** [comment]
Change requests have been implemented, see screenshot below.  Back to @DianaTavares to review, close if OK.

<img width="666" alt="screenshot_3515" src="https://github.com/user-attachments/assets/89b2c78a-a1ad-4424-9851-3b1a0bafadca">

**Comment by DianaTavares** [comment]
I looks amazing!! Closing!
