### ISSUE TITLE
modelModeProperty is confusing.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#66]
From the PhET-iO design document:

> `modelsOfTheHydrogenAtom.spectraScreen.model.modelModeProperty` This changes the scene between experiment/model, and I find the name strange (because it starts with the word “model” which is one of the options). Probably `sceneModeProperty`, or `modeProperty`? Or ask CM for ideas. NS also `model.model` looks strange.

**Comment by pixelzoom** [comment]
I initially created this issue in the wrong repo, so it was transferred from ph-scale to models-of-the-hydrogen-atom.

**Comment by DianaTavares** [comment]
I find isExperimentProperty very clear with boolean values! but leave @arouinfar to review because she has more experience with PhET-iO.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! The changes look good on main. I agree with @DianaTavares, `isExperimentProperty` is very clear.

Closing!
