### ISSUE TITLE
Invert colors for the Absorption/Emission checkbox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#69]
Reported by @Nancy-Salpepi in today's design meeting...

The Absorption/Emission checkbox currently looks like this:

<img width="198" alt="screenshot_3509" src="https://github.com/user-attachments/assets/5e0a8b80-aa3a-4fdb-94e7-dcef9ec456f5">

Inverting the colors, as in Kepler's Laws, would make the checkbox more readable on the black background (default color profile). For example:

<img width="174" alt="screenshot_3510" src="https://github.com/user-attachments/assets/37b18108-344a-40eb-8c11-4b0ea25fa714">

**Comment by pixelzoom** [comment]
Done in the above commits, see screenshots below for both color profiles. @Nancy-Salpepi please review, close if OK.

<img width="209" alt="screenshot_3512" src="https://github.com/user-attachments/assets/a48c6321-faf1-4f10-8e30-26ef522e6393">
<img width="201" alt="screenshot_3511" src="https://github.com/user-attachments/assets/3b77fa02-7783-4b2f-8fcf-43a56119e854">

**Comment by pixelzoom** [comment]
PS - These colors can also be adjusted in the ColorEditor:

```ts
  checkboxStrokeProperty: new ProfileColorProperty( modelsOfTheHydrogenAtom, 'checkboxStroke', {
    default: 'white',
    projector: 'black'
  } ),

  checkboxFillProperty: new ProfileColorProperty( modelsOfTheHydrogenAtom, 'checkboxFill', {
    default: 'black',
    projector: 'white'
  } ),
```

**Comment by Nancy-Salpepi** [comment]
Looks really nice now! Thanks for making the change @pixelzoom!
Wondering, is the checkbox bigger than usual?

**Comment by Nancy-Salpepi** [comment]
Either way is fine with me. 
Feel free to close!

**Comment by pixelzoom** [comment]
The checkbox is now sized to match the text height, see screenshot below.  Closing.

<img width="189" alt="screenshot_3514" src="https://github.com/user-attachments/assets/c7e8f0b5-958b-4e8b-95f7-5acfe42e8c2b">
