### ISSUE TITLE
projector mode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#7]
Does this sim need a "projector mode", as in rutherford-scattering? 

If so, please enumerate which user-interface elements need to change, and how they need to change.

**Comment by amyh-phet** [comment]
@pixelzoom   I think ideally a projector mode would be nice.  However, I recognize that many things such as icons for atomic models and spectrometer displays will not look good on a white background.  I'll look into how best to approach this and update here.

**Comment by pixelzoom** [comment]
Notes to self about implementation:
1. use scenery-phet.ColorProfile
2. support 2 profiles: default, projector
3. the query parameter should be `colorProfile=projector`
4. do we need to switch this dynamically via a 'Projector Mode' check box in Options dialog? (ala molecule-shapes)

**Comment by amyh-phet** [comment]
@pixelzoom  I do think switching dynamically via "Projector Mode" check box in Options dialog makes sense. Added projector mode mockups to design doc and included mockups in AI file.

**Comment by pixelzoom** [comment]
I the above commit, I added the Options dialog with "Projector Mode" checkbox, and basic support for color profiles in MOTHAColorProfile.   Still needed to (1) move colors into MOTHAColorProfile, and (2) specify what colors to use for projector mode.

**Comment by pixelzoom** [comment]
Fleshed out color profile some more in the above commits.

**Comment by pixelzoom** [comment]
Un-deferring, because development has resumed for this sim.

Status of this issue:
* MOTHAColors.ts contains color profiles for 'default' and 'projector'
* Projector Mode checkbox appears in the Options dialog, and it works
* Color Editor mode is supported in phetmarks

So I'm going to close this issue.  Adjusting the colors will be part of a more general issue, later in development.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.

**Comment by pixelzoom** [comment]
TODO removed. Closing.
