### ISSUE TITLE
Stimulated emission does not occur with Bohr model.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#70]
While investigating https://github.com/phetsims/models-of-the-hydrogen-atom/issues/57#issuecomment-2395567851, I noticed that stimulated emission never occurs for the Bohr model, and that seems incorrect. 

It does very occassionally for de Broglie, and I don't understand why, because `DeBroglieModel extends BohrModel`.  (Untested for Schrodinger, since it's not fully implemented yet.) 

Running with `?log` results in console output whenever emission (stimulated or spontaneous) occurs.

**Comment by pixelzoom** [comment]
I was incorrect. I added better logging output, and different halo color (green) for stimulated emission photons. And I can now confirm that it is indeed occurring.  But it occurs infrequently, and without `?debugEmission`, it's almost impossible to notice when it occurs, because photons released via stimulated emission travel in the same direction as the light source.  I'll take this up in #57.

Closing.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi and I discussed.  We're not clear on which type of emission is more common.  And concerned that stimulated emission is occurring very rarely, and difficult to see.

The model does things in this order. Is this correct?

* move the electron
* attempt spontaneous emission
* for each photon: move the photon, attempt absorption. If not absorbed, attempt stimulated emission.

**Comment by kathy-phet** [comment]
@pixelzoom @DianaTavares @Nancy-Salpepi @arouinfar - Stimulated emission has a number of factors that effect its ratio to spontaneous emission (light density being one of those factors). I do not personally see stimulated emission as one of this sim's learning goals - and it seems like a distraction to the main learning goals of this simulation. Stimulated emission is really well covered by the Laser sim, and is the central learning goal of that sim and shows the importance of this physics in context. My preference would be to not add it as a learning goal here. It also seems like it conflicts with the "see the emitted photon well" goal where we shoot the emitted photon off in a different direction so you can attend to it. 

@pixelzoom - did the Java MOTHA include stimulated emission? 

Happy to meet to discuss this design issue synchronously.

**Comment by Nancy-Salpepi** [comment]
I agree with @kathy-phet. I don't think stimulated emission should be one of the learning goals for this simulation, as it is not usually discussed when learning about the history of atomic theory and the modern model of the atom. At the high school level, one of the learning goals is usually to explain how a bright line spectrum is produced, which is described using spontaneous emission.

**Comment by pixelzoom** [comment]
> @pixelzoom - did the Java MOTHA include stimulated emission?

Yes. The HTML5 version is a direct port of the stimulated emission code from the Java version. And it behaved the same in the Java version -- infrequent and difficult to see.  

Not my call on whether it's a learning goal, but I did think it was important to bring up the usability issue.  Happy to close if the current behavior is sufficient.  Another alternative would be to remove the stimulated emission code -- it's a significant chunk of code, and if it's not desired then perhaps it should be deleted.

**Comment by kathy-phet** [comment]
I don't know the history, but this sim was developed after Lasers sim and Discharge Lamp sims I believe, so perhaps the stimulated emission piece was adopted from the models that drove those sims to some degree. 

I'm also happy to close this issue, or to remove the code from this sim and close (as long as it does not take much time, and if you recommend even though we WILL need it someday for Lasers sim). 

@DianaTavares - Do you have thoughts to add here?

**Comment by DianaTavares** [comment]
I like the idea to close the issue and leave the code the way it is. I am not also an expert teaching this topic, but looks like:
 1) that code is going to be useful for future sims, 
2) it is phenomena that really happen, then to have some stimulated emissions in the sim is more realistic.  Introductory teachers/students are not going to notice this stimulated emission happen, and advance teacher/students I think may be grateful that it is presented. 

And I will include a small paragraph of this in the teacher tips.

**Comment by DianaTavares** [comment]
I have a section in the design document, but probably is also nice to ad ain issue. 

![image](https://github.com/user-attachments/assets/70620ae8-2420-44bf-9b84-6a9647016e46)

I will close this one, and open an issue related to teacher tips.
