### ISSUE TITLE
Add a static summary for each screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#72]
From https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67#issuecomment-2436531739 ...

> @kathy-phet also requested that we add a static summary for reach screen. @jessegreenberg and I started some work related to that in https://github.com/phetsims/joist/issues/987.

I've implemented the code for this, with a placeholder string.  @DianaTavares @arouinfar can you please provide a static summary for each screen?

**Comment by arouinfar** [comment]
It's unclear to me what a "static summary" entails, so I've asked @kathy-phet for clarification on the MOTHA Slack channel.

The scene summary typically contains a highly dynamic paragraph that we refer to as the "dynamic state-of-sim". To make a static scene summary, we would need to skip this paragraph or design something VERY generic.

I think we should probably skip it because a generic/static state-of-sim is unlikely to be sufficiently different from the play area and control area paragraphs. We can keep it in mind while designing the scene summary, though.

**Comment by DianaTavares** [comment]
I wrote this two static summary in the [design document.](https://docs.google.com/document/d/1S4k58UnzQIypA2I2MD-iYPZ9DAeM_oClM5jXcLxw0YY/edit) (just before interactivity) Not sure if it is what is needed, but at least is something to look at and modify as needed: 

**Spectra screen**

Models of the hydrogen atom, Spectra Screen, is an interactive simulation that changes as you play with it. It has a  Play Area and a Control Area.

In the Play Area, you find a container with a hydrogen atom represented as an incognito box while the Experiment is selected. You can change the atom representation by changing from Experiment to Model and choosing one of the 6 different models. You can also turn on the light source to interact with the atom and experiment with white or monochromatic light.

In the Control Area is a Spectrometer that displays the photons emitted in a graph and offers options to save data. The play controls manipulate the reproduction velocity, and the reset button resets the simulation.


**Energy Levels screen**

The Models of the Hydrogen Atom, Energy Levels screen, is an interactive simulation that changes as you play with it. It has a Play Area and a Control Area.

In the Play Area, you find a container with a hydrogen atom. You can change the atom representation by choosing one of the 3 different models: Bohr, de Broglie, and Schrödinger. As the first screen, turn on the light source to interact with the atom, and experiment with white or monochromatic light. Open the Electron Energy Level to get more detailed information on the electron transition between levels and energy when it interacts with the light.

In the Control Area is a Spectrometer that displays the photons emitted in a graph and offers options to save data. The play controls manipulate the reproduction velocity, and the reset button resets the simulation.

**Comment by pixelzoom** [comment]
I've implemented @DianaTavares's initial proposal, so we have something to discuss, and so I could investigate the implementation issues.  You can test drive it in main using the A11y View. 

Designers should know that the current API allows you to set a `screenSummaryContent: Node`.  This appears in A11y View after the sentence "The {{SCREEN_NAME}} Screen changes as you play with it. It has a Play Area and a Control Area." and before the sentence "If needed, check out keyboard shortcuts under Sim Resources."  Those 2 sentences are provided by joist, and the sim programmer currently has no control over them.

Here's the current implementation for SpectraScreenView, which I consulted on with @jessegreenberg. Note that we're refining this API in https://github.com/phetsims/joist/issues/987.

```ts
      screenSummaryContent: new Node( {
        tagName: 'p',
        innerContent: ModelsOfTheHydrogenAtomStrings.a11y.spectraScreenSummaryStringProperty
      } ),
```

Here's the English value of `spectraScreenSummaryStringProperty` in the JSON strings file:

```json
    "spectraScreenSummary": {
      "value": "In the Play Area, you find a container with a hydrogen atom represented as an incognito box while the Experiment is selected. You can change the atom representation by changing from Experiment to Model and choosing one of the 6 different models. You can also turn on the light source to interact with the atom and experiment with white or monochromatic light.<p>In the Control Area is a Spectrometer that displays the photons emitted in a graph and offers options to save data. The play controls manipulate the reproduction velocity, and the reset button resets the simulation."
    },
```

And here's what it looks like in A11y View.  It looks like `innerContent` does not know what to do with HTML markup, so the `<p>` tag between paragraphs is displayed literally.   @jessegreenberg can you please advise on what to do here? Do I need to implement a more complex `screenSummaryContent` Node, or should it (or A11y View) be able to handle HTML markup?  If we'll be considering a static screen summary as part of "first tier" description support, then it would be nice to keep this simple for the sim programmer.

<img width="425" alt="screenshot_3551" src="https://github.com/user-attachments/assets/3278c4df-e262-445a-9a73-810315f4fbed">

**Comment by jessegreenberg** [comment]
> can you please advise on what to do here? Do I need to implement a more complex screenSummaryContent

Yes, you will need one Node for each paragraph. `innerContent` can't handle HTML for security reasons - especially for translations, rendering HTML from the string allows any kind of cross site scripting. To keep this simple we can add some support in https://github.com/phetsims/joist/issues/987.

**Comment by jessegreenberg** [comment]
ScreenSummaryContent is being used two create 2 paragraphs. @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
@arouinfar identified a 3rd paragraph -- the interaction hint -- to be included in the screens summaries.  I restructured the strings file so we now have this structure for each screen:

```json
"energyLevelsScreenSummary": {
      "playArea": {
        "value": "In the Play Area, ..."
      },
      "controlArea": {
        "value": "In the Control Area, ..."
      },
      "interactionHint": {
        "value": "Turn on the light source to explore."
      }
    },
```

Having such 3 paragraphs might be a good general/default design pattern for the static screen summary.  Something for discussion...

**Comment by arouinfar** [comment]
@DianaTavares @Nancy-Salpepi I iterated on the sections describing the Play Area and Control Area of the sim. I tried to minimize differences between the screens, and the Control Area is the same for both. Can you review?

**Spectra Screen**

The Play Area contains a light source aimed at a sample of hydrogen atoms. The observation window displays a zoomed-in view of a single hydrogen atom, which varies with the mode of exploration. In Experiment mode, the structure of the hydrogen atom is a mystery and is obscured. In Model mode, there are six different models of the hydrogen atom to explore, ranging from classical to quantum. Determine the structure of the hydrogen atom by shining white or monochromatic light on the sample.

The Control Area has a Spectrometer that displays a histogram of the photons emitted by the hydrogen atom. Take snapshots of the spectrometer data and compare up to four snapshots at a time. Control how fast the action happens in the observation window, including buttons to pause or step forward, and reset the sim.

**Energy Levels Screen**

he Play Area contains a light source aimed at a sample of hydrogen atoms.  The observation window displays a zoomed-in view of a single hydrogen atom, which varies with the mode of exploration. In Experiment mode, the structure of the hydrogen atom is a mystery and is obscured. In Model mode, there are three quantum models of the hydrogen atom to explore. Determine the structure of the hydrogen atom by shining white or monochromatic light on the sample. Observe changes in the electron’s state in the Electron Energy Level diagram.

The Control Area has a Spectrometer that displays a histogram of the photons emitted by the hydrogen atom. Take snapshots of the spectrometer data and compare up to four snapshots at a time. Control how fast the action happens in the observation window, including buttons to pause or step forward, and reset the sim.

**Comment by pixelzoom** [comment]
Nice. I added these new strings to the sim.  So @DianaTavares and @Nancy-Salpepi you can review "in context" in the A11y View.

**Comment by Nancy-Salpepi** [comment]
The descriptions look great @arouinfar! No suggested changes from me.

**Comment by pixelzoom** [comment]
A general issue related to any static description, but especially toith static screen summaries...  How does the static screen summary get adjusted based on PhET-iO customization?  

A few examples from the summary for this sum:

* "In Experiment mode" and "In Model mode" when the AB switch can be hidden.
* "there are six different models of the hydrogen atom to explore" when the number of models available can be change by hiding radio buttons, or the entire radio button group.
*  "The Control Area has a Spectrometer" when the entire Spectrometer accordion box can be hidden.
* "Take snapshots of the spectrometer data and compare up to four snapshots at a time." when the snapshot buttons can be hidden.
* "Control how fast the action happens" when PhET-iO allows you to hide the time controls.

... and many other customizations that result in incorrect description.

I see this same problem in the description work that's being done for pH Scale.  For example, none of the logic deals that derives a description considers what is actually visible in the user interface, how visibility of things in the user interface may dynamically change, etc.

I saw this problem every sim that I review that has both PhET-iO and description features -- Greenhouse Effect, Density, Buoyancy, Mean Share and Balance, ...

@kathy-phet @brent-phet There is a rather large conflict between the PhET-iO and description features.  And having to consider PhET-iO results in a complexity explosion.  Is it wise to make both PhET-iO and description part of the standard feature set before this has been addressed?

**Comment by pixelzoom** [comment]
@kathy-phet Since you suggested this feature, can you please review im the A11y View? Specifically:

* Is this what you had in mind for static screen summaries?
* Thoughts on the design pattern identified in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/72#issuecomment-2448464789.

**Comment by DianaTavares** [comment]
I already reviewed the static description and it looks great! nice work @arouinfar !!
Looks like this issue only need @kathy-phet review.

**Comment by kathy-phet** [comment]
> @kathy-phet Since you suggested this feature, can you please review in the A11y View? Specifically:
> 
> * Is this what you had in mind for static screen summaries?
> * Thoughts on the design pattern identified in [Add a static summary for each screen. #72 (comment)](https://github.com/phetsims/models-of-the-hydrogen-atom/issues/72#issuecomment-2448464789).

@pixelzoom @arouinfar @DianaTavares - 
Yes, the static screen summaries look great to me and are reaching the "context" setting goal I was hoping to have when a user first lands on this screen. Telling them what is available in general, but remaining static in nature. 

The design pattern looks good to me in that it provides good structure that matches the general design pattern for these screen summaries, so seems to me to be reaching the goal of a good reusable API that will support the sim devs and match the design patterns we have been using for this part of description. 

Thanks all!

**Comment by pixelzoom** [comment]
@terracoda This issue is ready for your review and feedback, including:

- [ ] Feedback on @kathy-phet's proposal to include a static screen summary as part of “tier 1” description support.
- [ ] Feedback on the general design pattern identified in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/72#issuecomment-2448464789.
- [ ] Review the specific screen summaries for this sim - you can see them in A11y View. Do you have any change requests?
- [ ] Anything else for this issue?

**Comment by terracoda** [comment]
Review in progress.

**Comment by pixelzoom** [comment]
11/7/24 design meeting: @DianaTavares @arouinfar @kathy-phet @terracoda @LindaStegemann @ariel-phet @KatieWoe @pixelzoom 

@arouinfar will clean up a couple of things in the existing summaries (e.g. "six models").

**Comment by arouinfar** [comment]
@pixelzoom @DianaTavares @Nancy-Salpepi 

I adjusted the scene summaries a bit, incorporating some of Taliesin's suggestions, reducing the frequency of "hydrogen atom", and removing references to the exact number of atomic models. I left the "compare up to four screenshots" language alone because this seems like useful information that isn't subject to change in PhET-iO (aside from maybe removing the ability to take screenshots altogether). The Control Area description is the same for both screens.

In general, I used proper nouns when referring to something by its accessible name, but there may be some accidental inconsistencies. @pixelzoom feel free to make grammatical changes as you see fit.

**Spectra Screen**

The Play Area contains a light source aimed at a sample of hydrogen atoms. The observation window displays a zoomed-in view of a single atom which varies with the mode of exploration. In Experiment mode, the atom’s structure is a mystery and is obscured. In Model mode, there are various models of the hydrogen atom to explore, ranging from classical to quantum. Determine the structure of the hydrogen atom by shining white or monochromatic light on the sample.

The Control Area has a Spectrometer that displays a histogram of the photons emitted by the hydrogen atom. Take snapshots of the spectrometer data and compare up to four snapshots at a time. Use Time Controls to adjust how fast the action happens in the observation window, including buttons to pause and step forward. Reset the sim to start over.

**Energy Levels Screen**

The Play Area contains a light source aimed at a sample of hydrogen atoms. The observation window displays a zoomed-in view of a single atom, which varies with the mode of exploration. In Experiment mode, the atom’s structure is a mystery and is obscured. In Model mode, there are various quantum models of the hydrogen atom to explore. Determine the structure of the hydrogen atom by shining white or monochromatic light on the sample. Observe changes in the electron’s state in the Electron Energy Level diagram.

The Control Area has a Spectrometer that displays a histogram of the photons emitted by the hydrogen atom. Take snapshots of the spectrometer data and compare up to four snapshots at a time. Use Time Controls to adjust how fast the action happens in the observation window, including buttons to pause and step forward. Reset the sim to start over.

**Comment by pixelzoom** [comment]
The number of snapshots is still a bit up in the air (constrained by vertical space, and how it ends up looking when I complete implementation) and may be affected by PhET-iO.   My crystal ball says that  4 snapshots will be cramped, and we’ll end up deciding on 3.  So I’d like to avoid putting “four” in the description.  With that in mind, we decided to change:

> Take snapshots of the spectrometer data and compare up to four snapshots at a time.

... to:

> Take snapshots of the spectrometer to compare data.


@arouinfar ready for your review. Please close if OK.

**Comment by arouinfar** [comment]
Looks good, closing!
