### ISSUE TITLE
Add "call to action" as helpText for screen buttons.

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/models-of-the-hydrogen-atom#73]
On the home screen, each screen button should have helptext that invites users to "explore ..." or something similar, mentioning briefly what that screen is about. Like this for GHE: 
![image](https://github.com/user-attachments/assets/f2eeb434-7a57-41e6-9290-39163ae1fc7e)

**Comment by kathy-phet** [comment]
Assigned Diana, Nancy, Amy - to design these helptext phrases for each screen.

**Comment by pixelzoom** [comment]
This is a change request related to https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67.

**Comment by DianaTavares** [comment]
I added a space in the design doc not to forget this help text, now each screen in the document has the next titles:

![image](https://github.com/user-attachments/assets/9971ce26-627a-4fa2-81ec-b9d4d96cc51b)

Well, that is to continue building a template for a design doc that considers all the things designers need to get ready for, including a basic A11y view. 

Talking about the helptext for Motha, I have this idea:

Screen 1 
Explore what may be the model of the Hydrogen Atom that better adjusts to the data generated by the interaction of the atom and light.

or something smaller:
Explore what Atom Models' data better adjusts to the Experiments' data.

Screen 2
Explore the changes in the electron’s state in the Electron Energy Level diagram.

**Comment by pixelzoom** [comment]
Looking at greenhouse-effect WavesScreen, here's the current API for specifying the helpText for the screen's associated buttons (on the home screen, and in the navigation bar):

```ts
      descriptionContent: GreenhouseEffectStrings.a11y.waves.homeScreenDescriptionStringProperty,
```

@arouinfar and I found `homeScreenDescriptionStringProperty` name to be very confusing, because it's not at all related to the Home screen/button.  But we will choose a better string key in MOTHA, and that's not related to the programming API.

`descriptionContent` for Screen is also confusing here.  Is this used only as the helpText for the buttons (home screen and navigation bar) associated with the screen, or is it used elsewhere.  @jessegreenberg If it's used only for the buttons, can we rename this option from `descriptionContent` to `screenButtonHelpText`?

**Comment by pixelzoom** [comment]
@DianaTavares Thanks for adding to the design doc template.  But for this:

> Helptext in home screen

It's actually "Helptext for screen buttons".  And those buttons appear on the Home screen, and in the navigation bar.

**Comment by pixelzoom** [comment]
So in ScreenView `SelfOptions`, the change would be:

```diff
- descriptionContent?: PDOMValueType | null;
+ // Help text that will be added to the Home screen button and navigation bar button for this screen.
+ descriptionContent?: PDOMValueType | null;
```

**Comment by jessegreenberg** [comment]
> f it's used only for the buttons, can we rename this option from descriptionContent to screenButtonsHelpText?

Yes! Was thinking the same thing, Ill note in https://github.com/phetsims/joist/issues/989

**Comment by arouinfar** [comment]
@DianaTavares @Nancy-Salpepi how about:

**Spectra Screen:** Compare experimental spectroscopy data to historical models of the hydrogen atom.

**Energy Levels Screen:** Observe changes in the electron’s state and compare to quantum models of the hydrogen atom.

**Comment by pixelzoom** [comment]
I've implemented helpText for the screen buttons using the API currently provided by `Screen`.

@jessegreenberg As you address https://github.com/phetsims/joist/issues/989, feel free to change `descriptionContent` to `screenButtonsHelpText` in SpectraScreen.ts and EnergyLevelsScreen.ts. 

I started with the helpText that @arouinfar proposed in https://github.com/phetsims/models-of-the-hydrogen-atom/issues/73#issuecomment-2457790013, easy to change.  Here's how it looks in A11y View:

<img width="647" alt="screenshot_3576" src="https://github.com/user-attachments/assets/9b06330c-87d9-4be9-bc93-b7d951b2764a">

**Comment by Nancy-Salpepi** [comment]
@arouinfar I like them both!  The only thing I don't love is the word "compare" for the Energy Levels screen. 
One alternative:
Explore electron transitions and relate observations to quantum models of the hydrogen atom.

**Comment by arouinfar** [comment]
> Explore electron transitions and relate observations to quantum models of the hydrogen atom.

Love it! Let's go with @Nancy-Salpepi's option if there are no objections.

**Comment by pixelzoom** [comment]
Updated as suggested by @Nancy-Salpepi.  Here's the A11y View:

<img width="638" alt="screenshot_3577" src="https://github.com/user-attachments/assets/69d73fe1-958f-4325-b8ab-bab72cc109b4">

**Comment by DianaTavares** [comment]
Love the text implemented!

**Comment by pixelzoom** [comment]
@DianaTavares @arouinfar and @Nancy-Salpepi have all reviewed and refined.  

I identifying API improvements, and @jessegreenberg is working on that in https://github.com/phetsims/joist/issues/989.  I've added TODOs in the MOTHA code, and @jessegreenberg should feel free to update MOTHA when he update the API.

@kathy-phet @terracoda Would you like to take a look before we close this issue? You can test drive in A11y View.

**Comment by terracoda** [comment]
Just adding the Home Screen for completeness. 
The helptext/calls-to-action look really great to me. 
![Screenshot 2024-11-05 at 17 25 42](https://github.com/user-attachments/assets/bc8c36c0-c8d3-4178-889d-83ee412c3982)

**Comment by kathy-phet** [comment]
Looks good to me. Thanks!

**Comment by pixelzoom** [comment]
Awesome, thanks everyone. Closing.
