### ISSUE TITLE
"Experiment or Model" ABSwitch requires common-code description work.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#74]
Related to #67 and  https://github.com/phetsims/scenery-phet/issues/880#issuecomment-2457658503 ... 

There is still work to be done on accessibleName for ABSwitch.  And that currently blocks MOTHA 1.0.

**Comment by pixelzoom** [comment]
@jessegreenberg did the development work in https://github.com/phetsims/scenery-phet/issues/880, I reviewed the work. Currently assigned to @terracoda to verify that the implementation matches the design expectations.

**Comment by terracoda** [comment]
From [#](https://github.com/phetsims/scenery-phet/issues/880#issuecomment-2471248475) I tested MacOS 14.5 Sonoma with VoiceOver, and I think the AB Switch works great.

Sounds good in Chrome, too. Tested with Version 129.0.6668.90 (Official Build) (arm64).

I would love a dev version to try it out with a screen reader user. I'll ask on slack.

**Comment by terracoda** [comment]
@pixelzoom, I verified the AB Switch with VoiceOver. I think this issue is unblocked.

**Comment by terracoda** [comment]
Is it ok to close this issue?

**Comment by pixelzoom** [comment]
Thanks @terracoda - closing!
