### ISSUE TITLE
Change description for Light Source.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#76]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67#issuecomment-2460594348, @terracoda said:

> **The Light Source interaction** is not being communicated as an on/off switch like in Molecules and Light. Are they not the same component?

They are not the same component. MOTHA uses scenery-phet's LaserPointerNode, which can be configured to use a RoundStickyToggleButton or RoundMomentaryButton. MAL has its own sim-specific component (no common code) called PhotonEmitterNode. It does some configuration of ARIA-related attributes, but I can't tell why or what parts are relevant for MOTHA -- there are no details in the code comments, and I can find no paper trail for the description design.

Also note that @jessegreenberg and I did considerable work on LaserPointerNode in https://github.com/phetsims/scenery-phet/issues/877. That work was informed by the requirements provided by the description designers in our 10/15/2 MOTHA meeting. If something different is desired, then that issue should be reopened, and a general solution (based on MAL PhotonEmitterNode?) implemented in LaserPointerNode.

**Comment by pixelzoom** [comment]
Also note that @jessegreenberg and I did considerable work on LaserPointerNode in https://github.com/phetsims/scenery-phet/issues/877.  That work was informed by the requirements provided by the description designers in our 10/15/2 MOTHA meeting.   If something different is desired, then that issue should be reopened, and a general solution (based on MAL PhotonEmitterNode?) implemented in LaserPointerNode.

**Comment by kathy-phet** [comment]
Initially, this looks like the common code RoundStickyToggleButton needs @jessegreenberg to work at the lower level scenery piece so the pdom implementation is appropriate for a sticky toggle kind of button.

**Comment by pixelzoom** [comment]
11/7/24 design meeting: @DianaTavares @arouinfar @kathy-phet @terracoda @LindaStegemann @ariel-phet @KatieWoe @pixelzoom 

@jessegreenberg will work on this.  Likely down in RoundStickyToggleButton. Should probably be `aria-role='switch'`.

**Comment by jessegreenberg** [comment]
This was done in https://github.com/phetsims/sun/issues/913.

**Comment by pixelzoom** [comment]
@jessegreenberg I'm unclear on how to review this.  Can you describe what the expected behavior is now?  I don't see anything different in A11y View --  I was expecting to see ARIA state showing whether the toggle is on/off, similar to what you did for the expand/collapse button in Accordion Box.  Or is there no change in A11y View, but change in screen reader behavior?

**Comment by pixelzoom** [comment]
Toclarify... For MOTHA A11y View, here's what I see for the light source toggle button:

<img width="122" alt="screenshot_3592" src="https://github.com/user-attachments/assets/96ea78a4-865e-4aaa-8d92-11ae3e496a48">

Here's what I see for an accordion box:

<img width="332" alt="screenshot_3593" src="https://github.com/user-attachments/assets/1766e956-54be-4680-b3da-12f93c7f581e">

So I was expecting to see a similar ARIA state for toggle button.

**Comment by jessegreenberg** [comment]
Correct, no visible changes in the a11y view yet - only screen reader behavior. The only aria attributes we display in the a11y view right now are aria-valuetext and aria-expanded. We will flesh that out in https://github.com/phetsims/chipper/issues/1510.

If you would like, you can confirm these attributes are there by inspecting in the page.
![image](https://github.com/user-attachments/assets/afdba8b6-b405-4c25-9e2a-e841cc006ca4)

**Comment by pixelzoom** [comment]
Understood, thanks. Closing.

**Comment by kathy-phet** [comment]
Using NVDA, it says whether its "On" and "Off" which is great!
