### ISSUE TITLE
Change helpText for "Absorption and Emission" checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#77]
In https://github.com/phetsims/models-of-the-hydrogen-atom/issues/67#issuecomment-2460594348, @terracoda said:

> Absorption/ Emission checkbox - @DianaTavares would it make sense to say "chart" or "table" in the name and/or help text instead of "dialog." Now that I have seen the content several times, the content looks like a single column or two column chart or table to me. For help text, I propose: 
* Show Absorption and Emission chart for electron state transitions and their associated wavelengths.

I recommend leaving as is, but defer to @DianaTavares.  It it important for the user to know that the chart/table will be displayed in a dialog?

**Comment by kathy-phet** [comment]
It's showing the dialog, so I would leave that, but add "table of"
Show Absorption and Emission dialog for [table of] electron state transitions and their associated wavelengths.

**Comment by pixelzoom** [comment]
11/7/24 design meeting: @DianaTavares @arouinfar @kathy-phet @terracoda @LindaStegemann @ariel-phet @KatieWoe @pixelzoom 

@kathy-phet suggested:
> Show Absorption and Emission dialog for [table of] electron state transitions and their associated wavelengths.

@pixelzoom will make it so.

**Comment by pixelzoom** [comment]
Done, shown in A11y View below.

<img width="441" alt="screenshot_3586" src="https://github.com/user-attachments/assets/e0835794-3500-41a3-a8be-1f26275342c7">
