### ISSUE TITLE
Revise icons for each model.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#8]
Redraw the icons for the models, as shown in this control panel:

![screenshot_22](https://cloud.githubusercontent.com/assets/3046552/18692433/45c3af10-7f57-11e6-8932-f2dabea3e466.png)

The icons from the Java version are all on black background, e.g.:

![billiardballbutton](https://cloud.githubusercontent.com/assets/3046552/18692458/7d592478-7f57-11e6-81d4-12f0209b2245.png)

To support a potential "projector mode" (#7) the icons should all be on transparent backgrounds, and should work on both the standard 'black' background, and whatever background color is desired in project mode.

The plum pudding icons should be revised to be consistent with the HTML5 version of rutherford-scattering.

**Comment by pixelzoom** [comment]
Also note that there is no asset (.ai) file for these icons in Unfuddle.  I don't recall how the PNG files were created - possibly by taking screenshots of the sim.

**Comment by amyh-phet** [comment]
@pixelzoom    Any size requirements for these icons?

**Comment by pixelzoom** [comment]
If you produce the .ai file, I can create the .png files.  The only requirement for the .ai file is that the icons should all have the same relative size.

**Comment by pixelzoom** [comment]
... and putting all of the icons in 1 .ai file (moths-model-icons.ai ?) will make things easiest for me.

**Comment by amyh-phet** [comment]
AI files emailed on 06/19/2017

**Comment by pixelzoom** [comment]
Thanks @amyh-phet, .ai file is checked in to github.

**Comment by pixelzoom** [comment]
I created new .png files from the .ai file.  These icons are going to need some more work.  See the comparison of Java icons and new icons in the screenshots below.

Before (Java png files):

<img width="309" alt="screenshot_1305" src="https://user-images.githubusercontent.com/3046552/62837263-e5b4f200-bc2a-11e9-8d94-ec39bddddd0f.png">

After (new png files):

<img width="311" alt="screenshot_1304" src="https://user-images.githubusercontent.com/3046552/62837270-f2394a80-bc2a-11e9-9e42-8af199b7fb6f.png">

**Comment by pixelzoom** [comment]
Un-deferring, because developer has resumed for this sim.

No assignment yet, until I determine whether these should be created programmatically, or whether artwork will be needed.

**Comment by pixelzoom** [comment]
All of the icons are now created programmatically, and there is no need for artwork.  So closing this issue.
