### ISSUE TITLE
Reuse visual strings for description in MOTHA.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#82]
Related to #67 ...

For description strings, we are currently using the approach that was used in MOTHA.  All description strings (accessibleNames and helpText) are under `ModelsOfTheHydrogenAtom.a11y` and no visual strings are reused. 

PhET is starting to build out support for default accessibleName, where the visual string is discovered and used for accessibleName.  Do we want to take advantage of this in MOTHA, or use MOTHA to prioritize building out this feature?

**Comment by pixelzoom** [comment]
11/7/24 design meeting: @DianaTavares @arouinfar @kathy-phet @terracoda @LindaStegemann @ariel-phet @KatieWoe @pixelzoom 

Consensus is yes.  @jessegreenberg and @pixelzoom will work on this.

**Comment by pixelzoom** [comment]
Here's an inventory of UI components used in MOTHA where `accessibleName` is the same as the visual string:

- [ ] ABSwitch (from `labelA` and `labelB` constructor args)
- [ ] AccordionBox (from `options.titleNode`)
- [ ] AquaRadioButton (from `labelNode` constructor args)
- [x] Checkbox (from `content` constructor arg)
- [ ] ComboBoxItem
- [x] Dialog (from `options.title`)
- [ ] RectangularRadioButton (from `options.content`)

@jessegreenberg does this help with identifying which common-code UI components to prioritize?

**Comment by jessegreenberg** [comment]
Yep, that is very helpful, thanks. Ill also make note of that in https://github.com/phetsims/sun/issues/911.

**Comment by pixelzoom** [comment]
Great. Keep me posted as the "discovery pattern" (`findStringProperty`) is added to UI components.  Then I'll remove strings from MOTHA that are the same as the default and therefore unnecessary.

**Comment by pixelzoom** [comment]
I've removed the strings that are now unnecessary (because they are discoverable). We are down to 12 strings for `accessibleName`.   We also have 10 strings for `helpText`.

I don't see any other opportunities for using defaults here, so I'll close this issue.
