### ISSUE TITLE
Add a reset button for Classical Solar System.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/models-of-the-hydrogen-atom#88]
The Classical Solar System model would benefit from having a reset button.  After the atom explodes, the only way to repeat is to select a different model, then select the Classical Solar System model again — not a good UX.

In addition to the button, we'll need:

* focus order
* accessibleName
* helpText

**Comment by pixelzoom** [comment]
The button has been implemented.  It appears in the lower-right corner of the box, and it is disabled until the atom has exploded. 

Assigning to @DianaTavares and @arouinfar to specify focus order, acessibleName, and helpText.

**Comment by DianaTavares** [comment]
When we talk about this button, I thought in one that appears when the atom crash, but this also works well! 

Focus order:
when it is visible, put it just after the Radio Button Group of Atomic Models: 
I update the design doc:
![image](https://github.com/user-attachments/assets/d7acab91-4a85-45a9-8b07-9ee8f875d0ba)

Accessible name: Reset Atom

Help text: I don't think it is needed. 

What do you think @pixelzoom? Amy is on vacation, if a second idea is needed, @Nancy-Salpepi have been helping us.

**Comment by pixelzoom** [comment]
Thanks @DianaTavares. What you proposed sounds good to me.  Please review in phettest, and feel free to close this issue if it looks OK.

**Comment by DianaTavares** [comment]
Perfect!
